### ISSUE TITLE
Multiply recipe incorrectly multiplies energy_required for default value

### ISSUE THREAD

**Issue by garrotte13** [brevven/foundry#10]
Hello,
while customizing my personal fork of your great mod I found this bug.
Attempt to multiple energy_required checks for it to be not nil
https://github.com/brevven/foundry/blob/main/data-util.lua#L688

If we know 100%, that recipe does exist (L687 does the check), then abscence of energy_required means it's value = 0.5. Therefore 
when check for nil returns nil (false), then energy_required value must be set like you do in L715, but multiple must be halved (implicit value of 0.5 multiplied by function parameter):
`recipe.energy_required = 0.5 * multiple`

**Comment by brevven** [comment]
Thanks! I'll fix this in my library that gets built into each mod, so you'll see it get fixed in each mod as it's updated. I may override the results for some recipes to not mess to much with ratios in existing factories.
